### ISSUE TITLE
Feature request: configurable emphasis range for Attention Grabber

### ISSUE THREAD

**Issue by feffy380** [adieyal/sd-dynamic-prompts#139]
The current implementation inserts values from 1.1 to 1.9.
I find going much higher than 1.5 often introduces artifacts and would like a config option for changing the range.

**Comment by adieyal** [comment]
Have a look at 1.5.1 - I've added two sliders and the defaults have changed to 1.1. - 1.5

**Comment by AncalagonX** [comment]
> Have a look at 1.5.1 - I've added two sliders and the defaults have changed to 1.1. - 1.5

The sliders don't seem to be affecting the attention grabber, and the attention grabber seems to be weighting its chosen tokens less than 1.0. Restated, all random attention grabber weights are between 0.0 and 0.99, so it's reducing their attention, rather than increasing it. For testing/troubleshooting, I removed all parenthesis/manually adjusted weights and was just using a simple plain text prompt.

Also, when you have time perhaps it would be a good idea to have a checkbox to enable attention grabber for positive prompts and another checkbox to enable it for negative prompts, rather than both at once. Overall I like the attention grabber idea in order to inject a bit more variability in my gens!

**Comment by adieyal** [comment]
Have a look at 1.5.9, the issue with the sliders should be fixed.
