### ISSUE TITLE
Doesn't work Any More in Automatic1111 Webui

### ISSUE THREAD

**Issue by zabinzsur** [adieyal/sd-dynamic-prompts#179]
Error loading script: dynamic_prompting.py
Traceback (most recent call last):
  File "E:\Diffusion_Auto_F111\stable-diffusion-webui\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "E:\Diffusion_Auto_F111\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "E:\Diffusion_Auto_F111\stable-diffusion-webui\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py", line 17, in <module>
    from dynamicprompts.wildcardmanager import WildcardManager
ModuleNotFoundError: No module named 'dynamicprompts'

This happened after updating dynamic-prompts to the latest version.

**Comment by Dravoss** [comment]
it is working in my machine, Web-UI and dynamic-prompts updated right now.

**Comment by adieyal** [comment]
Not sure why that happened, but it is because the dynamicprompts library wasn't installed for some reason. This was was an issue with the LastBen colab but I think it was resolved today. As a workaround, you can run `python -m pip install dynamicprompts`

What happens if you delete the extensions/sd-dynamic-prompts folder and reinstall?

**Comment by silvermike83** [comment]
Yeah, this one might be getting weird. I was getting htis issue, deleted the extension, reinstalled it, worked fine, reloaded a little later, and it was happening again.

**Comment by adieyal** [comment]
@silvermike83 - are you using a local install or a colab? If so, which one?

**Comment by Omenizer** [comment]
I'm also not getting it on TheLastBen colab.  The manual install works but I usually forget it...

**Comment by silvermike83** [comment]
I'm using Runpod

**Comment by zabinzsur** [comment]
After manually re-installing using git clone and then doing python -m pip install dynamicprompts on my PC, It worked.
That's not working on Collab though. If it helps, the other wildcard extension also fails in Collab.

If I update using the Automatic1111 Webui, then It will probably stop working again.

**Comment by barryanders** [comment]
> Not sure why that happened, but it is because the dynamicprompts library wasn't installed for some reason. This was was an issue with the LastBen colab but I think it was resolved today. As a workaround, you can run `python -m pip install dynamicprompts`
> 
> What happens if you delete the extensions/sd-dynamic-prompts folder and reinstall?

On Google Colab, I tried deleting it and got the same problem with a fresh install. Running the dynamic prompts python install line you left there fixed it for me. Thanks

**Comment by adieyal** [comment]
> If I update using the Automatic1111 Webui, then It will probably stop working again.

Could you confirm if that's the case. Once dynamicprompts is installed, updating the extension won't break it.

**Comment by adieyal** [comment]
> If it helps, the other wildcard extension also fails in Collab.

Is there an error?

**Comment by DarthMov** [comment]
> Not sure why that happened, but it is because the dynamicprompts library wasn't installed for some reason. This was was an issue with the LastBen colab but I think it was resolved today. As a workaround, you can run `python -m pip install dynamicprompts`
> 
> What happens if you delete the extensions/sd-dynamic-prompts folder and reinstall?

I tried to command you suggested in the AUTOMATIC1111 paper space install and that did not work at all. For whatever reason only parts of the dynamic prompt script wants to work. When I type {Platinum Ring|Gold Ring} into the prompt and set the batch size to five, I will get random assortments of gold and platinum rings, as it should. But when I input a prompt as simple as __ bird__ (I have a bird.txt file installed in the wild cards folder) it does not work at all. I know it doesn't because when I check the parameters info on each picture they all say "bird" instead of a random name of a bird from the birds.txt file. Does anyone know what's happening and why this occurs? I would really appreciate help with this. I've been trying to figure out why this doesn't work for the past 3 days and apparently even YouTube videos that have been made on this 2 months ago are already outdated.

**Comment by adieyal** [comment]
@DarthMov - I've responded to your issue here: https://github.com/adieyal/sd-dynamic-prompts/issues/186 which is different to the problem mentioned in this thread.

**Comment by adieyal** [comment]
I'm closing this issue because it has become a little convoluted with a number of different problems. If you are experiencing issues with installing on a colab, please post it here: https://github.com/adieyal/sd-dynamic-prompts/issues/187
