### ISSUE TITLE
Wildcard Abbreviations

### ISSUE THREAD

**Issue by pokeball99** [adieyal/sd-dynamic-prompts#240]
basically the ability to shorthand wildcard, so something like
`{devilkkw/attire/attire_uniforms_and_costumes}`
would become
`{d/a/acac}`
the only thing is i'm not quite sure what to use as the syntax to declare that you _are_ using an abbreviation, perhaps if the first character after __ is a /, like how Danbooru does it

maybe even have a special file for personally common abbreviations, such as `{/sf}` for `solo focus`

**Comment by akx** [comment]
Don't you mean `d/a/auac`? 😁 

Since wildcard files are parsed for other wildcard references, you should be able to make your own wildcard file, e.g. `x/ac` with the content `__devilkkw/attire/attire_uniforms_and_costumes__` and have it act as an alias you can then use with `__x/ac__`.

Alternately, if you're on an UNIX style system, you should be able to also use a symlink to another wildcard file...

**Comment by adieyal** [comment]
You might also find the globbing syntax helpful - https://github.com/adieyal/sd-dynamic-prompts#fuzzy-globrecursive-wildcard-filedirectory-matching

**Comment by akx** [comment]
Closing to tidy up the issue list; some solutions are above :)
