### ISSUE TITLE
[Feature Request] honor blank values in wildcard files

### ISSUE THREAD

**Issue by afbagwell** [adieyal/sd-dynamic-prompts#296]
Currently you can use a dynamic prompt to make a blank value possible like this:

`{red|blue|yellow|}`

where the final choice doesn't insert a value. This is really helpful for optional tokens.

From what I've experimented with there's no way to reproduce this in wildcard files. Blank lines are simply ignored, which is a good thing since they may not be intentional.

I'd suggest have a token in the file that can identify a empty string to be used such as:
```
red
blue
%EMPTY%
yellow
```
or whatever would be an easy way to declare an intentional blank possibility.

**Comment by adieyal** [comment]
How about something like `{__colours__|}`  

would that work for you?

I think it makes more sense than adding a dummy value to your wildcards file which represents a blank.

**Comment by adieyal** [comment]
You can use weights in your variants, e.g. `{0.3::red|0.7::blue}` which will produce red 30% of the time and blue 70% of the time.  Not mathematically correct, but you can do something like `{0.1::|0.9::__colours__}` that will produce a blank 10% of the time. 

With regards to complex prompts, you should use spaces and comments liberally, e.g. (it might not make sense how I broke it up, but might give you an idea of the best way to manage your prompt.
```
(high quality depth map),
# Personal characteristics
(medieval RPG, __region__ looking __lifestage__ __bodySex__ (__action__), {full body|}
character portrait, 
realistic detailed 

# Facial features
__eyeColor__ eyes, detailed __faceShape__ face:1.2),
({high depth dark|high depth light} __locations__ detailed background),
({long|medium||short} __hairColor__ __hairStyle__ hair:1.3),
# Body features
(__complexion__ skin:1.2),

# Other details
(__profession__),
(__race__:1.2),
(__theme__),
(__outfit__), 
({realistic weapon|no weapon}),
(__alignment__:1.2), 

# Styles
unity asset store,
full body shot,
(fantasy portraits, rpg portraits),
(professional majestic oil painting by fantasy art book illustrators, volumetric lighting:1.3),

# Modifiers
intricate,
high detail,
dramatic,

# Artists
by Anna Pavleeva and Valeriy Vegera
```

Comments are particularly useful if you want to try out different modifiers without removing them completely
e.g.

```
A painting by
artist1,
#artist2,
artist3
```

Here I comment out artist2 to see how it changes the output.

Finally, consider chunking your prompt into wildcard files which you can include in your main prompt. For instance, facial features might be common across many of your prompts, do this instead:

```
# facial_features.txt
__eyeColor__ eyes, detailed __faceShape__ face:1.2), ({high depth dark|high depth light} __locations__ detailed background),({long|medium||short} __hairColor__ __hairStyle__ hair:1.3),
```

Then in your main prompt:
```
(high quality depth map),
# Personal characteristics
(medieval RPG, __region__ looking __lifestage__ __bodySex__ (__action__), {full body|}
character portrait, 
realistic detailed

__facial_features__
...
```

That way you can build a complex system of prompts, rather than one big, hard-to-understand prompt.

**Comment by afbagwell** [comment]
This is all really great advice. Thanks!
You can close out this issue if the request doesn't fit your model of how wildcard files should work. It was just a suggestion.
Cheers!

**Comment by akx** [comment]
I wonder if you could just use strings that are ignored by the SD tokenizer - does eg a `...` in the prompt affect the output?

**Comment by adieyal** [comment]
Surprisingly `...` is not ignored, I'm sure there must be something, but since the tokenizer contains on the order of 40k-50k tokens, I would imagine that all  the basic stuff would  be included.

**Comment by Kadah** [comment]
Was looking to do this too, figured out a workaround to not having a dedicated no-op keyword.

This `(:0)` works for a no-op placeholder. A1111 will parse that to `weight nothing to zero`.

**Comment by HanaTakeno** [comment]
> Was looking to do this too, figured out a workaround to not having a dedicated no-op keyword.
> 
> This `(:0)` works for a no-op placeholder. A1111 will parse that to `weight nothing to zero`.

Was also looking to do this, sadly weighing something to 0 still seems to have an impact. Adding `(short hair:0)` on a very basic prompt still noticeably affected hair length over multiple generations, and the tokens still are added to the tokenizer causing other minor effects.
Least impactful option I've found so far has been to add a `,` option, resulting in a single comma. Still impacts the generation, but I think this has the smallest degree of change I've seen.
