### ISSUE TITLE
wildcard weighting options

### ISSUE THREAD

**Issue by sebastianhoerz** [adieyal/sd-dynamic-prompts#433]
I'm trying to get weighting in wildcards to work...  My .txt files recognize the e.g. 20::hat, 0.1::turban options. So it just gives out hat or turban but it doesnt adhere to the probability. Could it be because it interpretes each line as a own prompt? Is there some workaround to get it working besides using a normal dynamic prompt? Thanks!!!

**Comment by Pokis** [comment]
what if i've wrote (__gender__:1.1)  it would still not work?

**Comment by jjmenet** [comment]
after maintaining 37k+ characters prompt with dynamic prompts, I am considering moving my prompts into wildcards, like as instead of having 100+ lines of 'character selector' prompts in my entire prompt, just having a text file with 100+ line. while doing this, I found that weighted wildcards are not supported. it will be very convenient to me if wildcard supported weighting.

Thank you!

**Comment by akx** [comment]
> what if i've wrote `(__gender__:1.1)` it would still not work?

That would give you a random wildcard from `gender` with a prompt weight bias, so e.g. `(male:1.1)`, `(female:1.1)`. It wouldn't make one wildcard option more likely than the other, which is what this issue is (probably?!) about.

**Comment by freezerain** [comment]
while harder to mantain you can easely manipulate chance of word to be picekd by duplicating it. You can even go further and write a normalization script for precise chance control

**Comment by akx** [comment]
You can now specify wildcard weights in JSON and YAML wildcard files:

```yaml
foo:
  - 1::bear
  - 2::bag
  - 3::bleep
```

See https://github.com/adieyal/dynamicprompts/pull/97 for more details.
