### ISSUE TITLE
Style 1 broken if Dynamic Prompt enabled.

### ISSUE THREAD

**Issue by crackfoo** [adieyal/sd-dynamic-prompts#73]
Hi, 

I've found that if I have Dynamic Prompt enabled, the premade Style (under the generate button) I have selected in the dropdown, doesn't get applied. Seems only the Style 1 drop down, selections in the Style 2 dropdown are being applied.

Thanks

**Comment by prog0111** [comment]
Having a very similar problem, but for me it's both the style 1 and style 2 dropdowns.  After installing the extension, selected styles are no longer applied unless I click the other button to add them to my prompt.

**Comment by crstp** [comment]
Same here

**Comment by crackfoo** [comment]
yes, I did more testing and it seems any text in the prompt part of the styles.csv isn't being processed ( in either 1 or 2) with the dynamic prompt plugin enabled. It is the negative prompt text that is working from the styles drop down.

**Comment by adieyal** [comment]
Reading through the code, it looks like auto1111 applies the styles before passing the prompt to the extensions, which is why it is overridden. There are three options:

1. Apply styles to the raw prompt, then run the extension
2. Run the extension, then apply the styles to the generated prompts.
3. Simply press the "Apply selected styles to current prompt"

I don't use styles so I'm not sure which is better. The former is better if you want to apply the dynamic prompt syntax to your style. The latter if you want to ensure that the style is always appended to the generated prompt. This is relevant if you use Magic Prompt or I'm feeling lucky

Let me know your thoughts

**Comment by prog0111** [comment]
I'm sure everyone has their own workflow...  I have terrible memory, so I use an extensive list of styles with prompt words for all sorts of things.  I normally select several of those, applying them to the current prompt as I go.

Once the basic prompt is set up, I use the two drop downs to select extra things on/off at a whim.  I've made styles for glasses, for hair, for a more rendered look, and so on.  I'll generate until I get a good seed, use that, and then pick from the drop downs what extras I want to try adding to it.  Sometimes the whole image changes by tweaking the prompt this way, but it works out surprisingly often.

Right now I'm using the wildcards extension to randomize things and most of my styles have them.  If a style selected in the drop down has a wildcard in it, it's definitely processed when "Generate" is clicked.  Wildcards also seem to use the selected seed and will choose consistently when needed, which really helps.  I guess that sounds most like option 1 on the list (at least for me).

**Comment by stysmmaker** [comment]
If I had to pick one I feel like option 1 would be the expected behavior. To me it seems acceptable and even expected that Magic Prompt and I'm feeling lucky would modify the negative prompt entirely, in which case you would need to apply the style first if you want it. Hopefully I understand that correctly, since I happen to use styles and not Magic Prompt/I'm feeling lucky (at least yet) so I'm not as familiar with those.
Perhaps a toggle for option 1 and 2 is the most ideal (assuming that covers every scenario)?

**Comment by adieyal** [comment]
Could you please give v0.29.12 a whirl to see if it fixes this issue?

**Comment by stysmmaker** [comment]
Seems like it's working great for the normal/positive prompt now, but not the negative prompt. I assume a similar fix needs to be applied to that?

**Comment by adieyal** [comment]
Fixed - I didn't realise that styles had both a negative and positive component to them

**Comment by stysmmaker** [comment]
Looks to be working for both now -- thanks!
